name: Deploy

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://timcole.me
    steps:
      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: 66.57.183.138:13231
          endpoint_public_key: ${{ secrets.WIREGUARD_PEER_KEY }}
          ips: 10.69.4.112/32
          allowed_ips: 10.69.0.0/21
          private_key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
      - name: Setup kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          curl -sLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          echo "Installed kubectl"
          mkdir -p ~/.kube
          echo $KUBECONFIG | base64 -d > ~/.kube/config
      - name: Set image
        run: kubectl set image deploy/timcole-me timcole-me=ghcr.io/timcole/timcole.me:${{ github.sha }}
      - name: Wait for deployment
        run: kubectl rollout status deploy/timcole-me
