name: Build Update

on:
  push:
    branches: [ 🦄 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: latest,${{ github.sha }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: |
          "GITHUB_HASH=${{ github.sha }}"
        tags: ${{ steps.meta.outputs.tags }}
